#!/bin/bash
echo  Ip address
curl ipecho.net/plain ;

sleep 5

echo Local IP address ;
ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1'



